In [1]:
import os, sys

In [2]:
cwd = os.getcwd()
cwd

'/Users/badr/Documents/ETS/Hiv2021/PFE/VS/git/fake-news-detection/notebooks'

In [3]:
main_repository = os.path.join(cwd, os.pardir)

In [4]:
sys.path.append(os.path.join(main_repository, 'src'))

## Create Fasttext Object

In [5]:
from fasttext_model.FasttextModel import FasttextModel

In [6]:
Fasttext = FasttextModel(main_repository, 5)

## Prepare Data for Training

In [7]:
Fasttext.preprocess()

  0%|          | 0/5 [00:00<?, ?it/s]/Users/badr/Documents/ETS/Hiv2021/PFE/VS/git/fake-news-detection/notebooks/../src/Preprocessing.py:68: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array([nltk.word_tokenize(corpus[i]) for i in range(len(corpus))])
100%|██████████| 5/5 [06:15<00:00, 75.04s/it]


In [8]:
Fasttext.format()

100%|██████████| 5/5 [00:30<00:00,  6.08s/it]


## Training

In [9]:
Fasttext.train(learning_rate=0.0075, epochs=100)

100%|██████████| 5/5 [08:55<00:00, 107.05s/it]


## Testing

In [10]:
Fasttext.test()

100%|██████████| 5/5 [00:05<00:00,  1.10s/it]


In [11]:
Fasttext.precision

0.9320334068227929

# Testing on an article

In [7]:
text = """ Members of Congress may use campaign funds to hire bodyguards, FEC rules
(CNN) — Members of Congress can use campaign funds to hire bodyguards, federal election regulators ruled Thursday -- nearly three months after the violent January 6 siege on the US Capitol raised fresh concerns about lawmakers' safety.

The 5-1 vote by the Federal Election Commission allows lawmakers to use donors' money for "bona fide, legitimate, professional personal security" against threats that arise as part of their jobs.

The action came in response to a request from officials with the National Republican Congressional Committee and the National Republican Senatorial Committee and falls in line with previous FEC actions that allow politicians to use campaign money to upgrade security at their homes.
But the commission spent hours of their online meeting tussling over how to properly define security personnel after Democratic lawyers raised the specter of some lawmakers using donors' money to pay right-wing militia members.

In a Wednesday letter to the commission, Marc Elias and other attorneys representing Democratic campaign committees urged regulators to craft the rules narrowly so that "campaign funds are not improperly used to fund groups organized to harass and intimidate political opponents."

"In the past election cycle, some individuals who are now Members of Congress displayed troubling ties to extremist groups, including some self-proclaimed 'militias,' such as the Proud Boys, the Oath Keepers, and the Three Percenters," the Democratic lawyers wrote. "In some cases, these groups purported to provide 'security' at events attended by Congressional candidates and Members of Congress."

One Democrat on the commission, Ellen Weintraub, said she was concerned about lawmakers operating at a far remove from their constituents and that untrained guards could improperly block the public from engaging with elected officials.

"I never thought of us as a country where the leadership of the country had to be surrounded by armed guards and ... needed to keep the public at arm's length," Weintraub said.

But Jessica Furst Johnson, a lawyer representing the Republican campaign committees, said lawmakers have pressing security concerns.

The threats they face, she retorted, do not involve "people who are showing up at homes in the middle of the night to have a nice conservation about legislation. We are talking about situations where members are, unfortunately, feeling threatened with their children in their homes in the middle of the night." """.replace('\n', ' ')

In [21]:
text = """ After safety review, Health Canada says people shouldn't hesitate to get AstraZeneca vaccine

Pharmacist Mario Linaksita, right, administers the Oxford-AstraZeneca COVID-19 vaccine to Sharon Berringer, 56, at University Pharmacy in Vancouver on Thursday, April 1, 2021. (Darryl Dyck/Canadian Press)
Following reports of rare blood clotting events among some who have received the AstraZeneca vaccine, Health Canada officials said today they still believe the product is safe — and Canadians should have no qualms about rolling up their sleeves for it when the time comes.

Speaking to reporters at a technical briefing, Dr. Supriya Sharma, Health Canada's chief medical adviser, said there is a "very low risk" that some patients could develop blood clotting with low platelets following vaccination.

Sharma said that with a fourth wave of COVID-19 raging — and with the risk of hospitalization and death still much greater than the risk of developing clots following an AstraZeneca shot — the benefits of this vaccine clearly outweigh any risks.

"Get whatever vaccine is available to you. It's that simple. The longer you wait to get vaccinated, the longer you're not protected," Sharma said. "We know the risks of getting these side effects from the vaccine are very rare."

COVID clotting risk far higher, Sharma says

Pointing to evidence from the U.K., where the AstraZeneca shot has been administered 20 million times, Sharma said the chance of developing these clots is roughly 1 in 250,000.

While there are other numbers circulating about the frequency of these clots, Canada is relying on the British data because the U.K. has a robust safety monitoring system and has administered a lot of shots, Sharma said.

Meanwhile, Sharma said, the odds of developing a "regular" clot — and not this rare, vaccine-induced thrombocytopenia (VIPIT) in people with low platelets — are 1 in 5 for people hospitalized with COVID-19.

The risk of a woman between the ages of 15 and 45 developing any sort of blood clot is 1 in 3,300. If they take birth control, the odds are 1 in 1,600. If a woman is pregnant, the risk is 1 in 300, Sharma said.

"It is difficult to wrap your head around these abstract numbers and relative risks. We understand that," Sharma said. "The risk of regular clots with COVID is much, much higher and it's much, much higher than having this very severe clot."

Health Canada still has not definitively associated the AstraZeneca vaccine with these clots. Sharma said only that the shot was "probably" the reason why some people developed this condition.

WATCH: Health Canada's Dr. Supriya Sharma on the AstraZeneca vaccine


Dr. Supriya Sharma tells reporters the COVID threat is "real" and outweighs rare instances of blood clots reported with the AstraZeneca and Johnson and Johnson/Janssen vaccines. 1:39
Sharma said the department has updated the product label to warn would-be patients about the risk of developing these clots. Patients who receive the shot will be told to look out for symptoms — severe headaches, abdominal pain, leg pain or shortness of breath.

Sharma said that if regulators conclude at any time that the risks of the AstraZeneca shot outweigh its benefits, Health Canada won't hesitate to pull the vaccine's authorization.

She said it's not unusual for such very rare side effects to emerge when a vaccine has been given to such large numbers of people.

One woman in Quebec has developed clots after receiving the Covishield product, a biologically identical version of the AstraZeneca vaccine produced by the Serum Institute of India.

In approving the shot in late February, Health Canada regulators authorized the shot for all adults 18 and over.

Sharma said Health Canada still believes that the shot can be safely deployed in all adults regardless of age. However, the National Advisory Committee on Immunization (NACI) has recommended that provinces restrict access to adults over the age of 55 — for now.

Sharma said NACI is reviewing more real-world data now and could update its guidelines. """.replace('\n', ' ')

In [22]:
text

' After safety review, Health Canada says people shouldn\'t hesitate to get AstraZeneca vaccine  Pharmacist Mario Linaksita, right, administers the Oxford-AstraZeneca COVID-19 vaccine to Sharon Berringer, 56, at University Pharmacy in Vancouver on Thursday, April 1, 2021. (Darryl Dyck/Canadian Press) Following reports of rare blood clotting events among some who have received the AstraZeneca vaccine, Health Canada officials said today they still believe the product is safe — and Canadians should have no qualms about rolling up their sleeves for it when the time comes.  Speaking to reporters at a technical briefing, Dr. Supriya Sharma, Health Canada\'s chief medical adviser, said there is a "very low risk" that some patients could develop blood clotting with low platelets following vaccination.  Sharma said that with a fourth wave of COVID-19 raging — and with the risk of hospitalization and death still much greater than the risk of developing clots following an AstraZeneca shot — the b

In [17]:
import fasttext

In [23]:
f_model_path = os.path.join(
    Fasttext.model_path, 'fasttext', 'model_1')

model = fasttext.load_model(f_model_path)

In [24]:
model.predict(text)

(('__label__true',), array([0.6851089]))

In [48]:
text = """ Nolte: Whites Excluded, Illegal Aliens Qualify for Oakland’s $500 Month Payout Program 

Oakland, California, Mayor Libby Schaaf (D) announced a program that offers poor minority families $500 a month. Poor white families are excluded for the sin of being white. However, illegal aliens qualify.

Per the Daily Mail, “An estimated 10,000 of Oakland’s 435,000 population are white residents who live in poverty,” but they will receive nothing, and only because they are white.

Here is how you qualify for Oakland’s no-questions-asked $500 a month:

You must have at least one child
Your income must be at or below 50 percent of Oakland’s median income
You must not be white
The excuse for excluding whitey, per the far-left Associate Press, is that “White households in Oakland on average make about three times as much annually than black households[.]”

Yeah, but, um, 10,000 white households do not.

Okay, but they are still white. Duh.

The good news — if you’re a total lunatic — is that while poor whites are excluded based only on the fact they are white, illegal aliens do qualify for the $500 per month.  Per Yahoo, the $500 is not taxable “and undocumented and/or unsheltered individuals also qualify.”

Let me run that Yahoo sentence through the Orwellian translator: “illegal aliens and the homeless also qualify.”

Ah, but do white illegal aliens and white homeless people qualify?

Oh, and how do you prove you qualify? Is a racist ID required?

Do Asians qualify as “people of color,” or is this one more hate crime against them, just like all the other hate crimes against Asians that happen exclusively in Democrat-run cities?

What about a white person who is both homeless and an illegal alien; would this person qualify?

The city is going to try and get away with this blatant racism by claiming the fund being used for the $500 payouts is a private fund. We’ll see if that flies, not only with the people but with the Supreme Court.

Oakland is a shithole city and one that has been run exclusively by Democrats for some 50 years. If there’s a racism problem in Oakland, if there’s a “systemic racism” problem in Oakland, let’s try to remember who’s been in charge of that system for a half century.

The Daily Mail reports “Oakland’s homeless population rose by nearly 50 per cent between 2017 and 2019.” Well, with Democrats in charge for a half-century, whose fault is that? Out here in MAGA Land, in Rural America, we don’t have a homeless crisis.

Oakland closed 2020 with its highest murder rate in eight years; 102 people killed. Well, whose fault is that? Out here in Trump Land we don’t have a gun violence problem (even though we all own guns).

Last year, Oakland was named one of the most dangerous cities in America? Well, whose fault is that? Out here in Rural America, all of us Trumptards live in peace and brotherhood. No racial tensions. No riots. No mass shootings.

There’s just no question that one of the primary motives behind excluding whites from this $500 a month is to deliberately gin up racial hate and racial division and racial tensions, which is something else that is almost exclusive to Democrat-run cities.

Between the violence, the shitty schools, the deliberate gunning up of racial tensions, not to mention all the rioting led by the left-wing terrorists in Antifa and Black Lives Matter, these Democrat-run cities are deliberately tearing themselves apart.

No sympathy here.

You get what you vote for and the idiots of Oakland obviously enjoy racism and murder and poverty and chronic homelessness. They do keep voting for it.

No skin off my nose.

Life remains peaceful, clean, safe, colorblind, and serene in MAGA Country.
""".replace('\n', ' ')

In [49]:
model.predict(text)

(('__label__fake',), array([0.99911696]))

In [50]:
import pandas as pd
import numpy as np

In [51]:
sample = pd.read_excel('news_sample.xlsx')

In [52]:
sample

Article  \
0   Members of Congress may use campaign funds to ...   
1   Biden to unveil major new spending plans as De...   
2   Blinken suggests US won't take punitive action...   
3   One day before the Republican Party’s elite do...   
4   Erin O’Toole wanted Conservatives to affirm th...   
5   Western Canada: Supreme Court upholds Ottawa’s...   
6   US-China relations: Beijing’s plan for aviatio...   
7   West Coast Trail will reopen to Canadian hiker...   
8   iOS 14.5 beta 5 is now available to developer ...   
9   A New Snapshot of a Black Hole Reveals Its Mys...   
10  Canadiens acquire Eric Staal from the Buffalo ...   
11  Just 30 More Awesome Products That We Found Sc...   
12  Trump Releases Footage of Yet-to-Air 60 Minute...   
13  Source: Biden to Debate Wearing Brain Implant,...   
14  Vatican Cardinal: In a Globalized World, ‘Ther...   
15  Texas GOP Votes To Delete Its Gab Account Afte...   
16  Here Come The Global Vaccine Passports Vaccina...   
17  Nolte: Whites Excluded, Illegal Aliens Qualify...   

                                                 Link  \
0   https://www.cnn.com/2021/03/26/politics/campai...   
1          https://apple.news/AHAdrDeI2QsOHQvky_R6QKA   
2          https://apple.news/AATez8h0STMeO9_-cMUvl4w   
3          https://apple.news/AOpNgt6jzTFmO0SeiBeI_tA   
4          https://apple.news/AA7uTFp8pSPi_JyUAxkQLAw   
5          https://apple.news/AwReImVYORaqXxkN82-kYnQ   
6          https://apple.news/Ah-0sZKV0QKKmKUaMk8MklA   
7          https://apple.news/Axn6cI_0TRtK6r0gAH2oD0g   
8          https://apple.news/AvwAnqPIrRnmSwMTh0UQ2dg   
9          https://apple.news/A4-miuWiySUye_iTyOTS8uw   
10  https://www.nhl.com/canadiens/news/canadiens-a...   
11  https://www.buzzfeed.com/mayning/tiktok-produc...   
12  https://nymag.com/intelligencer/2020/10/trump-...   
13  https://nymag.com/intelligencer/2020/09/trump-...   
14  https://www.infowars.com/posts/vatican-cardina...   
15  https://www.infowars.com/posts/texas-gop-votes...   
16  https://www.infowars.com/posts/here-come-the-g...   
17  https://www.breitbart.com/politics/2021/03/26/...   

                                            Type  
0              Nouvelles americaines - Politique  
1              Nouvelles americaines - Politique  
2              Nouvelles americaines - Politique  
3              Nouvelles americaines - Politique  
4              Nouvelles canadiennes - Politique  
5              Nouvelles canadiennes - Politique  
6          Nouvelles internationales - Politique  
7   Nouvelles canadiennes locales - faits divers  
8                                Nouvelles tech   
9                              Nouvelles science  
10                               Nouvelles sport  
11                                      buzzfeed  
12                                          fake  
13                                          fake  
14                                          fake  
15                                          fake  
16                                          fake  
17                                          fake

In [53]:
sample_text = [article.replace('\n', ' ') for article in sample['Article'].to_numpy()]

In [54]:
prediction = model.predict(sample_text)
prediction

([['__label__true'],
  ['__label__true'],
  ['__label__true'],
  ['__label__true'],
  ['__label__fake'],
  ['__label__true'],
  ['__label__true'],
  ['__label__fake'],
  ['__label__fake'],
  ['__label__fake'],
  ['__label__fake'],
  ['__label__fake'],
  ['__label__fake'],
  ['__label__fake'],
  ['__label__fake'],
  ['__label__fake'],
  ['__label__true'],
  ['__label__fake']],
 [array([0.8655688], dtype=float32),
  array([0.92760366], dtype=float32),
  array([0.5219696], dtype=float32),
  array([0.9043543], dtype=float32),
  array([0.6802929], dtype=float32),
  array([0.5412521], dtype=float32),
  array([0.9857506], dtype=float32),
  array([0.5413083], dtype=float32),
  array([0.99955374], dtype=float32),
  array([0.9970895], dtype=float32),
  array([0.54190737], dtype=float32),
  array([0.990149], dtype=float32),
  array([0.9408776], dtype=float32),
  array([0.96281147], dtype=float32),
  array([0.696766], dtype=float32),
  array([0.9502674], dtype=float32),
  array([0.7410048], dtype=

In [55]:
sample['Résultat'] = prediction[0]
sample['Score'] = prediction[1]

In [56]:
sample

Article  \
0   Members of Congress may use campaign funds to ...   
1   Biden to unveil major new spending plans as De...   
2   Blinken suggests US won't take punitive action...   
3   One day before the Republican Party’s elite do...   
4   Erin O’Toole wanted Conservatives to affirm th...   
5   Western Canada: Supreme Court upholds Ottawa’s...   
6   US-China relations: Beijing’s plan for aviatio...   
7   West Coast Trail will reopen to Canadian hiker...   
8   iOS 14.5 beta 5 is now available to developer ...   
9   A New Snapshot of a Black Hole Reveals Its Mys...   
10  Canadiens acquire Eric Staal from the Buffalo ...   
11  Just 30 More Awesome Products That We Found Sc...   
12  Trump Releases Footage of Yet-to-Air 60 Minute...   
13  Source: Biden to Debate Wearing Brain Implant,...   
14  Vatican Cardinal: In a Globalized World, ‘Ther...   
15  Texas GOP Votes To Delete Its Gab Account Afte...   
16  Here Come The Global Vaccine Passports Vaccina...   
17  Nolte: Whites Excluded, Illegal Aliens Qualify...   

                                                 Link  \
0   https://www.cnn.com/2021/03/26/politics/campai...   
1          https://apple.news/AHAdrDeI2QsOHQvky_R6QKA   
2          https://apple.news/AATez8h0STMeO9_-cMUvl4w   
3          https://apple.news/AOpNgt6jzTFmO0SeiBeI_tA   
4          https://apple.news/AA7uTFp8pSPi_JyUAxkQLAw   
5          https://apple.news/AwReImVYORaqXxkN82-kYnQ   
6          https://apple.news/Ah-0sZKV0QKKmKUaMk8MklA   
7          https://apple.news/Axn6cI_0TRtK6r0gAH2oD0g   
8          https://apple.news/AvwAnqPIrRnmSwMTh0UQ2dg   
9          https://apple.news/A4-miuWiySUye_iTyOTS8uw   
10  https://www.nhl.com/canadiens/news/canadiens-a...   
11  https://www.buzzfeed.com/mayning/tiktok-produc...   
12  https://nymag.com/intelligencer/2020/10/trump-...   
13  https://nymag.com/intelligencer/2020/09/trump-...   
14  https://www.infowars.com/posts/vatican-cardina...   
15  https://www.infowars.com/posts/texas-gop-votes...   
16  https://www.infowars.com/posts/here-come-the-g...   
17  https://www.breitbart.com/politics/2021/03/26/...   

                                            Type         Résultat  \
0              Nouvelles americaines - Politique  [__label__true]   
1              Nouvelles americaines - Politique  [__label__true]   
2              Nouvelles americaines - Politique  [__label__true]   
3              Nouvelles americaines - Politique  [__label__true]   
4              Nouvelles canadiennes - Politique  [__label__fake]   
5              Nouvelles canadiennes - Politique  [__label__true]   
6          Nouvelles internationales - Politique  [__label__true]   
7   Nouvelles canadiennes locales - faits divers  [__label__fake]   
8                                Nouvelles tech   [__label__fake]   
9                              Nouvelles science  [__label__fake]   
10                               Nouvelles sport  [__label__fake]   
11                                      buzzfeed  [__label__fake]   
12                                          fake  [__label__fake]   
13                                          fake  [__label__fake]   
14                                          fake  [__label__fake]   
15                                          fake  [__label__fake]   
16                                          fake  [__label__true]   
17                                          fake  [__label__fake]   

           Score  
0    [0.8655688]  
1   [0.92760366]  
2    [0.5219696]  
3    [0.9043543]  
4    [0.6802929]  
5    [0.5412521]  
6    [0.9857506]  
7    [0.5413083]  
8   [0.99955374]  
9    [0.9970895]  
10  [0.54190737]  
11    [0.990149]  
12   [0.9408776]  
13  [0.96281147]  
14    [0.696766]  
15   [0.9502674]  
16   [0.7410048]  
17  [0.99911696]